# Generated by Django 2.2.5 on 2020-03-05 14:16

from django.db import migrations, models
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(choices=[('Mouse', 'MOUSE'), ('Keyboard', 'KEYBOARD'), ('Camera', 'CAMERA'), ('Shirt', 'SHIRT'), ('T Shirt', 'T-SHIRT'), ('Jeans', 'JEANS'), ('Trousers', 'TROUSERS'), ('Bat', 'BAT'), ('Ball', 'BALL'), ('Cap', 'CAP'), ('Pen', 'PEN'), ('Pen Holder', 'PEN HOLDER'), ('Paper Weight', 'PAPER WEIGHT'), ('White Board', 'WHITE BOARD'), ('Table Fan', 'TABLE FAN'), ('Showcase', 'SHOWCASE'), ('Air Purifier', 'AIR PURIFIER')], default='Mouse', max_length=25)),
                ('seller_name', models.CharField(max_length=50, null=True)),
                ('s_name', models.CharField(max_length=50, null=True)),
                ('p_img', smartfields.fields.ImageField(upload_to='pics/')),
                ('p_price', models.CharField(max_length=10)),
                ('min_q', models.CharField(max_length=10)),
                ('p_desc', models.TextField(null=True)),
                ('tag', models.CharField(max_length=20, null=True)),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UsersRated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=50, null=True)),
                ('rate', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(to='seller.UsersRated')),
            ],
        ),
    ]
