# Generated by Django 2.2.5 on 2019-12-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('p_img', models.ImageField(upload_to='pics')),
                ('p_price', models.CharField(max_length=10)),
                ('min_q', models.CharField(max_length=10)),
            ],
        ),
    ]
