# Generated by Django 2.2.5 on 2020-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='seller_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
