# Generated by Django 2.2.5 on 2020-03-10 07:33

from django.db import migrations
import seller.models
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='p_img',
            field=smartfields.fields.ImageField(upload_to=seller.models.get_name),
        ),
    ]
