# Generated by Django 2.2.5 on 2020-03-10 10:36

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200310_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='p_img2',
            field=smartfields.fields.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='productdata',
            name='p_img3',
            field=smartfields.fields.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='productdata',
            name='p_img4',
            field=smartfields.fields.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='p_img',
            field=smartfields.fields.ImageField(upload_to='pics'),
        ),
    ]
