# Generated by Django 2.2.5 on 2020-01-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200117_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='p_id',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
