# Generated by Django 2.2.5 on 2020-01-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_productdata_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='p_id',
        ),
    ]
