# Generated by Django 2.2.5 on 2020-02-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20200211_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='s_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
