# Generated by Django 2.2.5 on 2020-02-14 12:55

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_productdata_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='p_img',
            field=smartfields.fields.ImageField(upload_to='pics'),
        ),
    ]
