# Generated by Django 2.2.5 on 2020-02-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_auto_20200214_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
