# Generated by Django 2.2.5 on 2020-02-24 07:14

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_productdata_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='p_img',
            field=smartfields.fields.ImageField(upload_to='pics/'),
        ),
    ]
