# Generated by Django 2.2.5 on 2020-03-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20200224_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
                ('seller', models.CharField(max_length=50, null=True)),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
    ]
