# Generated by Django 2.2.5 on 2020-03-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='rating',
            name='users',
            field=models.ManyToManyField(to='seller.UsersRated'),
        ),
    ]
