# Generated by Django 2.2.5 on 2020-03-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_q', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, null=True)),
                ('p_name', models.ManyToManyField(to='seller.ProductData')),
                ('quant', models.ManyToManyField(to='carts.Quantity')),
            ],
        ),
    ]
