# Generated by Django 2.2.5 on 2020-02-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0009_auto_20200224_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, null=True)),
                ('p_name', models.ManyToManyField(to='seller.ProductData')),
            ],
        ),
    ]
