# Generated by Django 2.2.5 on 2020-02-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcart',
            name='quant',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
