# Generated by Django 2.2.5 on 2020-02-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_pcart_quant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcart',
            name='quant',
        ),
    ]
