# Generated by Django 2.2.5 on 2020-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_pcart_quant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_q', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='pcart',
            name='quant',
            field=models.ManyToManyField(to='carts.Quantity'),
        ),
    ]
