# Generated by Django 2.2.5 on 2020-03-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdata',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
